spring:
    security:
        user:
            name: test   # ???
            password: 123456  # ??
            roles:   # ??
                - user
                - admin
    datasource:
        url: jdbc:mysql://localhost:3306
        username: root
        password: qsm12104214
        driver-class-name:  com.mysql.cj.jdbc.Driver

    mail:
        # 163??????smtp.163.com???????
        host: smtp.qq.com
        # ????163??
        username: shuminque@qq.com
        # ????????smtp/pop3?????????????????????
        password: bawerassliehbcef
    mvc:
        static-path-pattern: /static/**